### ISSUE TITLE
Improve error logs

### ISSUE THREAD

**Issue by NomadBlacky** [NomadBlacky/digdag-plugin-datadog#8]
Execute the below workflow with an invalid API key.

```yaml
_export:
  plugin:
    dependencies:
      - dev.nomadblacky:digdag-plugin-datadog_2.13:0.1.0

+example:
  datadog_event>:
    title: "[TEST] digdag-plugin-datadog"
    text: "Digdag meets Datadog!!"
```

```
$ digdag run --no-save datadog.dig
2019-11-10 23:11:29 +0900: Digdag v0.9.39
2019-11-10 23:11:30 +0900 [INFO] (main): Database migration started
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20151204221156
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160602123456
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160602184025
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160610154832
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160623123456
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160719172538
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160817123456
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160818043815
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160818220026
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160908175551
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160926123456
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20160928203753
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20161005225356
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20161028112233
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20161110112233
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20161209001857
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20170116082921
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20170116090744
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20170223220127
2019-11-10 23:11:30 +0900 [INFO] (main): Applying database migration:20190318175338
2019-11-10 23:11:30 +0900 [INFO] (main): Database migration successfully finished.
2019-11-10 23:11:31 +0900 [WARN] (main): Reusing the last session time 2019-11-10T00:00:00+00:00.
2019-11-10 23:11:31 +0900 [INFO] (main): Starting a new session project id=1 workflow name=datadog session_time=2019-11-10T00:00:00+00:00
2019-11-10 23:11:32 +0900 [INFO] (0016@[0:default]+datadog+example): datadog_event>: {title=[TEST] digdag-plugin-datadog, text=Digdag meets Datadog!!}
2019-11-10 23:11:32 +0900 [INFO] (0016@[0:default]+datadog+example): Start the datadog_event operation.
2019-11-10 23:11:33 +0900 [ERROR] (task-thread-0): Uncaught exception. Task queue will detect this failure and this task will be retried later.
scaladog.api.DatadogApiException: 403 Forbidden: <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

        at scaladog.api.APIClient.request(APIClient.scala:41)
        at scaladog.api.APIClient.httpPost(APIClient.scala:23)
        at scaladog.api.APIClient.httpPost$(APIClient.scala:22)
        at scaladog.api.events.EventsAPIClientImpl.httpPost(EventsAPIClient.scala:42)
        at scaladog.api.events.EventsAPIClientImpl.postEvent(EventsAPIClient.scala:74)
        at dev.nomadblacky.digdag.plugin.datadog.operator.DatadogEventOperator.runTask(DatadogEventOperator.scala:26)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

This stack trace outputted to STDOUT.  
So it is invisible in Digdag UI.

![2019-11-10_23-08](https://user-images.githubusercontent.com/3215961/68545405-4c0b0580-0410-11ea-9832-26652d9d6df2.png)

**Comment by NomadBlacky** [comment]
I fixed to use `TaskExecutionException`, it can put error logs.

https://github.com/NomadBlacky/digdag-plugin-datadog/blob/815638aae1ec9515039b49ba98cc8fb249b599d4/src/main/scala/dev/nomadblacky/digdag/plugin/datadog/operator/event/DatadogEventOperator.scala#L37

![スクリーンショット 2019-12-20 19 34 03](https://user-images.githubusercontent.com/3215961/71249055-b4c69580-235f-11ea-9f25-e4671b47fe15.png)
